USE [CZ2O05_152804_PR_PD]
GO

/****** Object:  View [dbo].[SellHelp]    Script Date: 07/07/2023 16:49:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[SellHelp] AS
SELECT
	SD.D2_EMISSAO,
	SD.D2_FILIAL FILIAL,
	SD.D2_DOC NF,
	CASE
		WHEN D2_DOC IN (SELECT D1_NFORI FROM SD1010) THEN 'D'
		ELSE 'N'
	END AS TIPONF,
	SD.D2_COD COD_PODUTO,
	SB.B1_DESC,
	SD.D2_PRCVEN PRVEN,
	SB.B1_GRUPO,
	SBM.BM_DESC,
	CASE
		WHEN D2_DOC IN (SELECT D1_NFORI FROM SD1010) THEN SD.D2_QUANT * (-1)
		ELSE SD.D2_QUANT * 1
	END AS QUANTIDADE,
	CASE
		WHEN D2_DOC IN (SELECT D1_NFORI FROM SD1010) THEN SD.D2_VALBRUT * (-1)
		ELSE SD.D2_VALBRUT
	END VENDA,
	SD.D2_CUSTO1 CUSTO,
	CASE
		WHEN SD.D2_CF NOT IN('5949', '6102') THEN (SD.D2_ICMFRET)
		ELSE 0
	END ST,
	SD.D2_PICM PICM,
	SD.D2_VALIMP6 PIS,
	SD.D2_VALIMP5 COFINS,
	SD.D2_VALICM ICMS,
	SD.D2_DESCZFC - SD.D2_DESCZFP DESCONTO,
	SD.D2_PEDIDO PEDIDO,
	SD.D2_CF CFOP,
	SD.D2_CLIENTE COD_CLIENTE,
	SA.A1_CGC,
	SA.A1_NOME CLIENTE,
	SA.A1_TPESSOA TPESSOA,
	SC.C5_TIPOCLI,
	SC.C5_VEND1,
	CASE 
		WHEN SC.C5_VEND1 = SV.A3_COD THEN SV.A3_NREDUZ
		ELSE ''
	END VENDEDOR1,
	SC.C5_VEND2,
	CASE 
		WHEN SC.C5_VEND2 = SV.A3_COD THEN SV.A3_NREDUZ
		ELSE ''
	END VENDEDOR2,
	SV.A3_GEREN,
	SF.F4_DUPLIC,
	SD1.D1_DOC NFORI
FROM SD2010 SD
	LEFT JOIN SF4010 SF
		ON 
			SF.F4_CODIGO = SD.D2_TES
			AND SF.F4_FILIAL = SUBSTRING(SD.D2_FILIAL,1,4)
	INNER JOIN SA1010 AS SA 
		ON SA.A1_COD = SD.D2_CLIENTE
	FULL OUTER JOIN SC5010 SC 
		ON SC.C5_NUM = SD.D2_PEDIDO
		AND SC.C5_FILIAL = SD.D2_FILIAL
	LEFT JOIN SD1010 AS SD1 
		ON
			SD1.D1_NFORI = SD.D2_DOC
			AND SD1.D1_FILIAL = SD.D2_FILIAL
			AND SD1.D1_COD = SD.D2_COD
	LEFT JOIN SA3010 SV
		ON SV.A3_COD = SC.C5_VEND1
	INNER JOIN SB1010 SB
		ON SB.B1_COD = SD.D2_COD
	INNER JOIN SBM010 SBM 
		ON SBM.BM_GRUPO = SB.B1_GRUPO
		AND SBM.D_E_L_E_T_ = ''
GO


